/**
 * Trade orders submitted by the user.
**/
DROP TABLE IF EXISTS client_orders;
CREATE TABLE IF NOT EXISTS client_orders (
  id UUID PRIMARY KEY, -- Generated by orders_service
  symbol text,
  price NUMERIC NOT NULL,
  order_size NUMERIC NOT NULL
)
