version: '3'
services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    restart: always
    volumes:
      - ./api_gateway:/api_gateway
      - /api_gateway/venv/         # mounts as an empty folder.
    environment:
      - ORDER_SERVICE_PORT=$ORDER_SERVICE_PORT
    ports:
    - $API_GATEWAY_PORT:$API_GATEWAY_PORT
    networks:
      - simplebank

  fees_service:
    container_name: fees_service
    build: ./fees_service
    restart: always
    volumes:
      - ./fees_service:/go/src/github.com/simplebank/fees_service/
    networks:
      - simplebank
    depends_on:
      - order_event_queue

  market_service:
    container_name: market_service
    build: ./market_service
    restart: always
    volumes:
      - ./market_service:/market_service
    environment:
      - ORDER_EQ_PASSWORD=$ORDER_EQ_PASSWORD
      - ORDER_EQ_PORT=$ORDER_EQ_PORT
      - ORDER_EQ_USER=$ORDER_EQ_USER
    networks:
      - simplebank
    depends_on:
      - order_event_queue

  order_db:
    container_name: order_db
    build: ./order_db
    restart: always
    environment:
      - POSTGRES_DB=$ORDER_DB_NAME
      - POSTGRES_PASSWORD=$ORDER_DB_PASSWORD
      - POSTGRES_USER=$ORDER_DB_USER
    expose:
    - $ORDER_DB_PORT
    networks:
      - simplebank

  order_event_queue:
    container_name: order_event_queue
    image: rabbitmq:3-management
    restart: always
    ports:
    - $ORDER_EQ_ADMINER_PORT:$ORDER_EQ_ADMINER_PORT
    volumes:
      - ./order_event_queue:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=$ORDER_EQ_USER
      - RABBITMQ_DEFAULT_PASS=$ORDER_EQ_PASSWORD
    networks:
     - simplebank

  order_service:
    container_name: order_service
    build: ./order_service
    restart: always
    volumes:
      - ./order_service:/order_service
      - /order_service/venv/           # mounts as an empty folder.
    environment:
      - DB_NAME=$ORDER_DB_NAME
      - DB_PASSWORD=$ORDER_DB_PASSWORD
      - DB_PORT=$ORDER_DB_PORT
      - DB_USER=$ORDER_DB_USER
      - ORDER_EQ_PASSWORD=$ORDER_EQ_PASSWORD
      - ORDER_EQ_PORT=$ORDER_EQ_PORT
      - ORDER_EQ_USER=$ORDER_EQ_USER
      - ORDER_SERVICE_PORT=$ORDER_SERVICE_PORT
    expose:
    - $ORDER_SERVICE_PORT
    networks:
      - simplebank

networks:
  simplebank:
