version: '3'
services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    restart: always
    volumes:
      - ./api_gateway:/api_gateway
      - /api_gateway/venv/         # mounts as an empty folder.
    environment:
      - ORDER_SERVICE_PORT=$ORDER_SERVICE_PORT
    ports:
    - $API_GATEWAY_PORT:$API_GATEWAY_PORT
    networks:
      - simplebank
    depends_on:
        - "logstash"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  fees_service:
    container_name: fees_service
    build: ./fees_service
    restart: always
    volumes:
      - ./fees_service:/go/src/github.com/simplebank/fees_service/
    networks:
      - simplebank
    depends_on:
      - order_event_queue

  market_service:
    container_name: market_service
    build: ./market_service
    restart: always
    volumes:
      - ./market_service:/market_service
    environment:
      - ORDER_EQ_PASSWORD=$ORDER_EQ_PASSWORD
      - ORDER_EQ_PORT=$ORDER_EQ_PORT
      - ORDER_EQ_USER=$ORDER_EQ_USER
    networks:
      - simplebank
    depends_on:
      - order_event_queue

  order_db:
    container_name: order_db
    build: ./order_db
    restart: always
    environment:
      - POSTGRES_DB=$ORDER_DB_NAME
      - POSTGRES_PASSWORD=$ORDER_DB_PASSWORD
      - POSTGRES_USER=$ORDER_DB_USER
    expose:
    - $ORDER_DB_PORT
    networks:
      - simplebank

  order_event_queue:
    container_name: order_event_queue
    image: rabbitmq:3-management
    restart: always
    ports:
    - $ORDER_EQ_ADMINER_PORT:$ORDER_EQ_ADMINER_PORT
    volumes:
      - ./order_event_queue:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=$ORDER_EQ_USER
      - RABBITMQ_DEFAULT_PASS=$ORDER_EQ_PASSWORD
    networks:
     - simplebank

  order_service:
    container_name: order_service
    build: ./order_service
    restart: always
    volumes:
      - ./order_service:/order_service
      - /order_service/venv/           # mounts as an empty folder.
    environment:
      - DB_NAME=$ORDER_DB_NAME
      - DB_PASSWORD=$ORDER_DB_PASSWORD
      - DB_PORT=$ORDER_DB_PORT
      - DB_USER=$ORDER_DB_USER
      - ORDER_EQ_PASSWORD=$ORDER_EQ_PASSWORD
      - ORDER_EQ_PORT=$ORDER_EQ_PORT
      - ORDER_EQ_USER=$ORDER_EQ_USER
      - ORDER_SERVICE_PORT=$ORDER_SERVICE_PORT
    expose:
    - $ORDER_SERVICE_PORT
    networks:
      - simplebank

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - "9200:9200"
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - simplebank
    
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"
    depends_on:
      - "elasticsearch"
    networks:
      - simplebank
    
  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    ports:
      - "25826:25826"
    volumes:
      - $PWD/elk-config:/elk-config
    command: logstash -f /elk-config/logstash.config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - "elasticsearch"
    networks:
      - simplebank

networks:
  simplebank:
