# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='order_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13order_service.proto\"?\n\x0cOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"\x1f\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"h\n\x13OrderStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\"\x17\n\x15OrderStatusAllRequest\">\n\x16OrderStatusAllResponse\x12$\n\x06orders\x18\x01 \x03(\x0b\x32\x14.OrderStatusResponse2z\n\x05Order\x12.\n\x0b\x43reateOrder\x12\r.OrderRequest\x1a\x0e.OrderResponse\"\x00\x12\x41\n\x0cGetAllOrders\x12\x16.OrderStatusAllRequest\x1a\x17.OrderStatusAllResponse\"\x00\x62\x06proto3')
)




_ORDERREQUEST = _descriptor.Descriptor(
  name='OrderRequest',
  full_name='OrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='OrderRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='OrderRequest.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='OrderRequest.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=86,
)


_ORDERRESPONSE = _descriptor.Descriptor(
  name='OrderResponse',
  full_name='OrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='OrderResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=119,
)


_ORDERSTATUSRESPONSE = _descriptor.Descriptor(
  name='OrderStatusResponse',
  full_name='OrderStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='OrderStatusResponse.order_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='OrderStatusResponse.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='OrderStatusResponse.symbol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='OrderStatusResponse.amount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='OrderStatusResponse.status', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=225,
)


_ORDERSTATUSALLREQUEST = _descriptor.Descriptor(
  name='OrderStatusAllRequest',
  full_name='OrderStatusAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=250,
)


_ORDERSTATUSALLRESPONSE = _descriptor.Descriptor(
  name='OrderStatusAllResponse',
  full_name='OrderStatusAllResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='OrderStatusAllResponse.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=314,
)

_ORDERSTATUSALLRESPONSE.fields_by_name['orders'].message_type = _ORDERSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['OrderRequest'] = _ORDERREQUEST
DESCRIPTOR.message_types_by_name['OrderResponse'] = _ORDERRESPONSE
DESCRIPTOR.message_types_by_name['OrderStatusResponse'] = _ORDERSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['OrderStatusAllRequest'] = _ORDERSTATUSALLREQUEST
DESCRIPTOR.message_types_by_name['OrderStatusAllResponse'] = _ORDERSTATUSALLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), dict(
  DESCRIPTOR = _ORDERREQUEST,
  __module__ = 'order_service_pb2'
  # @@protoc_insertion_point(class_scope:OrderRequest)
  ))
_sym_db.RegisterMessage(OrderRequest)

OrderResponse = _reflection.GeneratedProtocolMessageType('OrderResponse', (_message.Message,), dict(
  DESCRIPTOR = _ORDERRESPONSE,
  __module__ = 'order_service_pb2'
  # @@protoc_insertion_point(class_scope:OrderResponse)
  ))
_sym_db.RegisterMessage(OrderResponse)

OrderStatusResponse = _reflection.GeneratedProtocolMessageType('OrderStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _ORDERSTATUSRESPONSE,
  __module__ = 'order_service_pb2'
  # @@protoc_insertion_point(class_scope:OrderStatusResponse)
  ))
_sym_db.RegisterMessage(OrderStatusResponse)

OrderStatusAllRequest = _reflection.GeneratedProtocolMessageType('OrderStatusAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _ORDERSTATUSALLREQUEST,
  __module__ = 'order_service_pb2'
  # @@protoc_insertion_point(class_scope:OrderStatusAllRequest)
  ))
_sym_db.RegisterMessage(OrderStatusAllRequest)

OrderStatusAllResponse = _reflection.GeneratedProtocolMessageType('OrderStatusAllResponse', (_message.Message,), dict(
  DESCRIPTOR = _ORDERSTATUSALLRESPONSE,
  __module__ = 'order_service_pb2'
  # @@protoc_insertion_point(class_scope:OrderStatusAllResponse)
  ))
_sym_db.RegisterMessage(OrderStatusAllResponse)



_ORDER = _descriptor.ServiceDescriptor(
  name='Order',
  full_name='Order',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=316,
  serialized_end=438,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOrder',
    full_name='Order.CreateOrder',
    index=0,
    containing_service=None,
    input_type=_ORDERREQUEST,
    output_type=_ORDERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllOrders',
    full_name='Order.GetAllOrders',
    index=1,
    containing_service=None,
    input_type=_ORDERSTATUSALLREQUEST,
    output_type=_ORDERSTATUSALLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDER)

DESCRIPTOR.services_by_name['Order'] = _ORDER

# @@protoc_insertion_point(module_scope)
