// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_service.proto

package order_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{0}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type OrderResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{1}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type OrderStatusResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatusResponse) Reset()         { *m = OrderStatusResponse{} }
func (m *OrderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*OrderStatusResponse) ProtoMessage()    {}
func (*OrderStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{2}
}

func (m *OrderStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusResponse.Unmarshal(m, b)
}
func (m *OrderStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusResponse.Marshal(b, m, deterministic)
}
func (m *OrderStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusResponse.Merge(m, src)
}
func (m *OrderStatusResponse) XXX_Size() int {
	return xxx_messageInfo_OrderStatusResponse.Size(m)
}
func (m *OrderStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusResponse proto.InternalMessageInfo

func (m *OrderStatusResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderStatusResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderStatusResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderStatusResponse) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type OrderStatusAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatusAllRequest) Reset()         { *m = OrderStatusAllRequest{} }
func (m *OrderStatusAllRequest) String() string { return proto.CompactTextString(m) }
func (*OrderStatusAllRequest) ProtoMessage()    {}
func (*OrderStatusAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{3}
}

func (m *OrderStatusAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusAllRequest.Unmarshal(m, b)
}
func (m *OrderStatusAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusAllRequest.Marshal(b, m, deterministic)
}
func (m *OrderStatusAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusAllRequest.Merge(m, src)
}
func (m *OrderStatusAllRequest) XXX_Size() int {
	return xxx_messageInfo_OrderStatusAllRequest.Size(m)
}
func (m *OrderStatusAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusAllRequest proto.InternalMessageInfo

type OrderStatusAllResponse struct {
	Orders               []*OrderStatusResponse `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OrderStatusAllResponse) Reset()         { *m = OrderStatusAllResponse{} }
func (m *OrderStatusAllResponse) String() string { return proto.CompactTextString(m) }
func (*OrderStatusAllResponse) ProtoMessage()    {}
func (*OrderStatusAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a121d2d2ec3d32, []int{4}
}

func (m *OrderStatusAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusAllResponse.Unmarshal(m, b)
}
func (m *OrderStatusAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusAllResponse.Marshal(b, m, deterministic)
}
func (m *OrderStatusAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusAllResponse.Merge(m, src)
}
func (m *OrderStatusAllResponse) XXX_Size() int {
	return xxx_messageInfo_OrderStatusAllResponse.Size(m)
}
func (m *OrderStatusAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusAllResponse proto.InternalMessageInfo

func (m *OrderStatusAllResponse) GetOrders() []*OrderStatusResponse {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "OrderResponse")
	proto.RegisterType((*OrderStatusResponse)(nil), "OrderStatusResponse")
	proto.RegisterType((*OrderStatusAllRequest)(nil), "OrderStatusAllRequest")
	proto.RegisterType((*OrderStatusAllResponse)(nil), "OrderStatusAllResponse")
}

func init() { proto.RegisterFile("order_service.proto", fileDescriptor_93a121d2d2ec3d32) }

var fileDescriptor_93a121d2d2ec3d32 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x9b, 0x86, 0xa4, 0x70, 0x6d, 0x19, 0x5c, 0x48, 0x42, 0xa7, 0xca, 0x0b, 0x19, 0x90,
	0x87, 0xf2, 0x04, 0x11, 0x12, 0xa8, 0x13, 0x52, 0x18, 0x18, 0xab, 0x94, 0xdc, 0x50, 0xc9, 0xad,
	0x8b, 0xed, 0x20, 0xc1, 0x5b, 0xf0, 0xc6, 0x28, 0xb6, 0xa9, 0xdc, 0x2a, 0x19, 0xbf, 0xbb, 0xd3,
	0xaf, 0xef, 0xee, 0x60, 0x26, 0x64, 0x8d, 0x72, 0xad, 0x50, 0x7e, 0x6d, 0x3f, 0x90, 0x1d, 0xa4,
	0xd0, 0x82, 0xbe, 0xc3, 0xe4, 0xb5, 0x2d, 0x97, 0xf8, 0xd9, 0xa0, 0xd2, 0x24, 0x85, 0x51, 0xa3,
	0x50, 0xae, 0xb7, 0x75, 0x16, 0x2c, 0x82, 0xfc, 0xaa, 0x8c, 0x5b, 0x5c, 0xd5, 0x24, 0x81, 0x58,
	0x7d, 0xef, 0x36, 0x82, 0x67, 0x43, 0x5b, 0xb7, 0xd4, 0xd6, 0xab, 0x9d, 0x68, 0xf6, 0x3a, 0x0b,
	0x17, 0x41, 0x1e, 0x95, 0x8e, 0xe8, 0x3d, 0x4c, 0x5d, 0xb0, 0x3a, 0x88, 0xbd, 0x42, 0x13, 0xa0,
	0x2b, 0xdd, 0xa8, 0xff, 0x60, 0x4b, 0xf4, 0x37, 0x80, 0x99, 0x99, 0x7c, 0x33, 0x7c, 0x9c, 0xbf,
	0x83, 0x4b, 0x2b, 0x7c, 0x54, 0x19, 0x19, 0x5e, 0xd5, 0xbe, 0xe4, 0xb0, 0x47, 0x32, 0xec, 0x91,
	0xbc, 0xf0, 0x25, 0x3d, 0xa7, 0xe8, 0xc4, 0x29, 0x85, 0x5b, 0x4f, 0xa9, 0xe0, 0xdc, 0x9d, 0x87,
	0x3e, 0x43, 0x72, 0xde, 0x70, 0xba, 0x0f, 0x10, 0x1b, 0xbd, 0x76, 0xbd, 0x30, 0x1f, 0x2f, 0x6f,
	0x58, 0xc7, 0x52, 0xa5, 0x9b, 0x59, 0xfe, 0x40, 0x64, 0xda, 0x84, 0xc1, 0xf8, 0x49, 0x62, 0xa5,
	0xd1, 0xe2, 0x94, 0xf9, 0xdf, 0x98, 0x5f, 0xb3, 0x93, 0x1b, 0xd2, 0x01, 0x29, 0x60, 0xf2, 0x82,
	0xba, 0xe0, 0xdc, 0x34, 0x14, 0x49, 0x58, 0xa7, 0xe8, 0x3c, 0x65, 0xdd, 0x9e, 0x74, 0xb0, 0x89,
	0xcd, 0xe7, 0x1f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x3d, 0x1b, 0xa1, 0x10, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	GetAllOrders(ctx context.Context, in *OrderStatusAllRequest, opts ...grpc.CallOption) (*OrderStatusAllResponse, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetAllOrders(ctx context.Context, in *OrderStatusAllRequest, opts ...grpc.CallOption) (*OrderStatusAllResponse, error) {
	out := new(OrderStatusAllResponse)
	err := c.cc.Invoke(ctx, "/Order/GetAllOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error)
	GetAllOrders(context.Context, *OrderStatusAllRequest) (*OrderStatusAllResponse, error)
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetAllOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderStatusAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetAllOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/GetAllOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetAllOrders(ctx, req.(*OrderStatusAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "GetAllOrders",
			Handler:    _Order_GetAllOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_service.proto",
}
