# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from . import order_service_pb2 as order__service__pb2


class OrderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateOrder = channel.unary_unary(
        '/Order/CreateOrder',
        request_serializer=order__service__pb2.OrderRequest.SerializeToString,
        response_deserializer=order__service__pb2.OrderResponse.FromString,
        )
    self.GetAllOrders = channel.unary_unary(
        '/Order/GetAllOrders',
        request_serializer=order__service__pb2.OrderStatusAllRequest.SerializeToString,
        response_deserializer=order__service__pb2.OrderStatusAllResponse.FromString,
        )


class OrderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateOrder': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOrder,
          request_deserializer=order__service__pb2.OrderRequest.FromString,
          response_serializer=order__service__pb2.OrderResponse.SerializeToString,
      ),
      'GetAllOrders': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllOrders,
          request_deserializer=order__service__pb2.OrderStatusAllRequest.FromString,
          response_serializer=order__service__pb2.OrderStatusAllResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Order', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
